services:
  valkey:
    image: valkey/valkey:8
    pull_policy: always

  # VS Code workspace service
  workspace:
    image: ghcr.io/techarohq/anubis/devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      cache_from:
        - "type=registry,ref=ghcr.io/techarohq/anubis/devcontainer"
    volumes:
      - ../:/workspace/anubis:cached
    #entrypoint: ["/usr/bin/sleep", "infinity"]
    user: vscode
